# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'EmployeeDirectoryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeDirectoryApp
	pod 'AFNetworking', '~> 4.0'
	pod 'SDWebImage', '~> 5.0'

  target 'EmployeeDirectoryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
